Repository ma-alps/spec, pull requests merged in 2021-06, with the labels that each got.

#26 Add MyAlps json schema and example.
  example/MyAlps.json
  schema/MyAlps.json
Labels: enhancement

#30 Update ASD to 0.6
  composer.json
  composer.lock
Labels: enhancement

#31 Add choreography title & doc
  docs/docs/idempotent.doCreateStateDiagram.html
  docs/docs/idempotent.doDelete.html
  docs/docs/idempotent.doEdit.html
  docs/docs/safe.goAlpsItem.html
  docs/docs/safe.goAlpsItemEdit.html
  docs/docs/safe.goIndex.html
  docs/docs/safe.goMyAlps.html
  docs/docs/safe.goUser.html
  docs/docs/semantic.AlpsItem.html
  docs/docs/semantic.AlpsItemEdit.html
  docs/docs/semantic.Index.html
  docs/docs/semantic.MyAlps.html
  docs/docs/semantic.User.html
  docs/docs/unsafe.doCreate.html
  docs/index.html
  docs/profile.xml
Labels: enhancement

#35 Fix example
  example/MyAlps.json
  example/doCreate.json
  schema/MyAlps.json
  schema/doCreate.json
Labels: enhancement

#33 Add doCreateStateDiagram json schema
  example/doCreateStateDiagram.json
  schema/doCreateStateDiagram.json
Labels: enhancement

#32 Add index json schema and example
  example/Index.json
  schema/Index.json
Labels: enhancement

#41 Add goIndex JsonSchema
  example/goIndex.json
  schema/goIndex.json
Labels: JsonSchema, enhancement

#40 Update AlpsItem
  docs/docs/safe.goAsd.html
  docs/docs/safe.goProfile.html
  docs/docs/semantic.AlpsItem.html
  docs/docs/semantic.Asd.html
  docs/docs/semantic.Profile.html
  docs/index.html
  docs/profile.dot
  docs/profile.svg
  docs/profile.xml
  example/AlpsItem.json
  schema/AlpsItem.json
Labels: JsonSchema, enhancement, profile

#46 Update asd
  composer.json
  composer.lock
  docs/docs/asd.html
  docs/docs/idempotent.doCreateStateDiagram.html
  docs/docs/idempotent.doDelete.html
  docs/docs/idempotent.doEdit.html
  docs/docs/safe.goAlpsItem.html
  docs/docs/safe.goAlpsItemEdit.html
  docs/docs/safe.goAlpsProfile.html
  docs/docs/safe.goAsd.html
  docs/docs/safe.goIndex.html
  docs/docs/safe.goProfile.html
  docs/docs/semantic.AlpsItem.html
  docs/docs/semantic.AlpsItemEdit.html
  docs/docs/semantic.AlpsList.html
  docs/docs/semantic.AlpsProfile.html
  docs/docs/semantic.Asd.html
  docs/docs/semantic.Index.html
  docs/docs/semantic.Profile.html
  docs/docs/semantic.StateDiagram.html
  docs/docs/semantic.User.html
  docs/docs/semantic.alpsItemId.html
  docs/docs/semantic.id.html
  docs/docs/semantic.isPublic.html
  docs/docs/semantic.mediaType.html
  docs/docs/semantic.profileFile.html
  docs/docs/semantic.repository.html
  docs/docs/semantic.title.html
  docs/docs/semantic.userId.html
  docs/docs/unsafe.doCreate.html
  docs/index.html
Labels: enhancement

#44 Add doDelete json schema
  schema/request/doDelete.json
  schema/request/example/doDelete.json
Labels: JsonSchema, enhancement

#51 Add JsonSchema goProfile.json
  schema/request/example/goProfile.json
  schema/request/goProfile.json
Labels: JsonSchema, enhancement

#50 Add JsonSchema goAlpsItemEdit
  schema/request/doCreate.json
  schema/request/example/goAlpsItemEdit.json
  schema/request/goAlpsItemEdit.json
Labels: JsonSchema, enhancement

#47 Add schema/goAlpsItem
  schema/request/example/goAlpsItem.json
  schema/request/goAlpsItem.json
Labels: JsonSchema, enhancement

#49 Fix alpsList & user
  docs/docs/semantic.alpsList.html
  docs/docs/semantic.user.html
Labels: bug

#43 Add AlpsItemEdit json schema
  docs/docs/semantic.asdUrl.html
  docs/docs/semantic.profileUrl.html
  docs/index.html
  docs/profile.xml
  schema/response/AlpsItem.json
  schema/response/AlpsItemEdit.json
  schema/response/example/AlpsItem.json
  schema/response/example/AlpsItemEdit.json
  schema/response/example/Index.json
  schema/response/example/Profile.json
Labels: JsonSchema, enhancement

#52 Add JsonSchema doEdit.json
  schema/request/doEdit.json
  schema/request/example/doEdit.json
Labels: JsonSchema, enhancement

#54 Feature/add json schema link
  composer.json
  composer.lock
  docs/docs/idempotent.doCreateStateDiagram.html
  docs/docs/idempotent.doDelete.html
  docs/docs/idempotent.doEdit.html
  docs/docs/safe.goAlpsItem.html
  docs/docs/safe.goAlpsItemEdit.html
  docs/docs/safe.goIndex.html
  docs/docs/safe.goProfile.html
  docs/docs/semantic.AlpsItem.html
  docs/docs/semantic.AlpsItemEdit.html
  docs/docs/semantic.Index.html
  docs/docs/semantic.Profile.html
  docs/docs/semantic.alpsList.html
  docs/docs/semantic.user.html
  docs/docs/unsafe.doCreate.html
  docs/index.html
  docs/profile.xml
  docs/schema/def/alpsList.json
  docs/schema/def/user.json
  docs/schema/request/doCreate.json
  docs/schema/request/doCreateStateDiagram.json
  docs/schema/request/doDelete.json
  docs/schema/request/doEdit.json
  docs/schema/request/example/doCreate.json
  docs/schema/request/example/doCreateStateDiagram.json
  docs/schema/request/example/doDelete.json
  docs/schema/request/example/doEdit.json
  docs/schema/request/example/goAlpsItem.json
  docs/schema/request/example/goAlpsItemEdit.json
  docs/schema/request/example/goIndex.json
  docs/schema/request/example/goProfile.json
  docs/schema/request/goAlpsItem.json
  docs/schema/request/goAlpsItemEdit.json
  docs/schema/request/goIndex.json
  docs/schema/request/goProfile.json
  docs/schema/response/AlpsItem.json
  docs/schema/response/AlpsItemEdit.json
  docs/schema/response/Index.json
  docs/schema/response/Profile.json
  docs/schema/response/example/AlpsItem.json
  docs/schema/response/example/AlpsItemEdit.json
  docs/schema/response/example/Index.json
  docs/schema/response/example/Profile.json
  schema
Labels: enhancement, profile, refactor

#37 Add doc & title to ontology & taxonomy
  docs/docs/idempotent.doEdit.html
  docs/docs/semantic.AlpsItem.html
  docs/docs/semantic.AlpsItemEdit.html
  docs/docs/semantic.Index.html
  docs/docs/semantic.Profile.html
  docs/docs/semantic.StateDiagram.html
  docs/docs/semantic.alpsList.html
  docs/docs/semantic.id.html
  docs/docs/semantic.user.html
  docs/docs/unsafe.doCreate.html
  docs/index.html
  docs/profile.xml
Labels: enhancement, profile

#56 Update asd
  composer.json
  composer.lock
  docs/docs/semantic.AlpsItem.html
  docs/profile.dot
  docs/profile.svg
  docs/profile.xml
Labels: enhancement
